// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// timezone-info.cpp
writable::doubles get_tz_offset(const doubles& posixct, const strings& zone);
extern "C" SEXP _mixtime_get_tz_offset(SEXP posixct, SEXP zone) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_tz_offset(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(posixct), cpp11::as_cpp<cpp11::decay_t<const strings&>>(zone)));
  END_CPP11
}
// timezone-info.cpp
writable::strings get_tz_abbreviation(const doubles& posixct, const strings& zone);
extern "C" SEXP _mixtime_get_tz_abbreviation(SEXP posixct, SEXP zone) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_tz_abbreviation(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(posixct), cpp11::as_cpp<cpp11::decay_t<const strings&>>(zone)));
  END_CPP11
}
// timezone-info.cpp
writable::list get_tz_transitions(const double start_posixct, const double end_posixct, const std::string& zone_name);
extern "C" SEXP _mixtime_get_tz_transitions(SEXP start_posixct, SEXP end_posixct, SEXP zone_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_tz_transitions(cpp11::as_cpp<cpp11::decay_t<const double>>(start_posixct), cpp11::as_cpp<cpp11::decay_t<const double>>(end_posixct), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(zone_name)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mixtime_get_tz_abbreviation", (DL_FUNC) &_mixtime_get_tz_abbreviation, 2},
    {"_mixtime_get_tz_offset",       (DL_FUNC) &_mixtime_get_tz_offset,       2},
    {"_mixtime_get_tz_transitions",  (DL_FUNC) &_mixtime_get_tz_transitions,  3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mixtime(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
