// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// timeastro.cpp
doubles approx_sunrises_from_utc(doubles unix_times, double lon_deg, double lat_deg, double alt_deg);
extern "C" SEXP _mixtime_approx_sunrises_from_utc(SEXP unix_times, SEXP lon_deg, SEXP lat_deg, SEXP alt_deg) {
  BEGIN_CPP11
    return cpp11::as_sexp(approx_sunrises_from_utc(cpp11::as_cpp<cpp11::decay_t<doubles>>(unix_times), cpp11::as_cpp<cpp11::decay_t<double>>(lon_deg), cpp11::as_cpp<cpp11::decay_t<double>>(lat_deg), cpp11::as_cpp<cpp11::decay_t<double>>(alt_deg)));
  END_CPP11
}
// timeastro.cpp
doubles approx_utc_from_sunrises(doubles sunrise_counts, double lon_deg, double lat_deg, double alt_deg);
extern "C" SEXP _mixtime_approx_utc_from_sunrises(SEXP sunrise_counts, SEXP lon_deg, SEXP lat_deg, SEXP alt_deg) {
  BEGIN_CPP11
    return cpp11::as_sexp(approx_utc_from_sunrises(cpp11::as_cpp<cpp11::decay_t<doubles>>(sunrise_counts), cpp11::as_cpp<cpp11::decay_t<double>>(lon_deg), cpp11::as_cpp<cpp11::decay_t<double>>(lat_deg), cpp11::as_cpp<cpp11::decay_t<double>>(alt_deg)));
  END_CPP11
}
// timeastro.cpp
doubles approx_sunsets_from_utc(doubles unix_times, double lon_deg, double lat_deg, double alt_deg);
extern "C" SEXP _mixtime_approx_sunsets_from_utc(SEXP unix_times, SEXP lon_deg, SEXP lat_deg, SEXP alt_deg) {
  BEGIN_CPP11
    return cpp11::as_sexp(approx_sunsets_from_utc(cpp11::as_cpp<cpp11::decay_t<doubles>>(unix_times), cpp11::as_cpp<cpp11::decay_t<double>>(lon_deg), cpp11::as_cpp<cpp11::decay_t<double>>(lat_deg), cpp11::as_cpp<cpp11::decay_t<double>>(alt_deg)));
  END_CPP11
}
// timeastro.cpp
doubles approx_utc_from_sunsets(doubles sunset_counts, double lon_deg, double lat_deg, double alt_deg);
extern "C" SEXP _mixtime_approx_utc_from_sunsets(SEXP sunset_counts, SEXP lon_deg, SEXP lat_deg, SEXP alt_deg) {
  BEGIN_CPP11
    return cpp11::as_sexp(approx_utc_from_sunsets(cpp11::as_cpp<cpp11::decay_t<doubles>>(sunset_counts), cpp11::as_cpp<cpp11::decay_t<double>>(lon_deg), cpp11::as_cpp<cpp11::decay_t<double>>(lat_deg), cpp11::as_cpp<cpp11::decay_t<double>>(alt_deg)));
  END_CPP11
}
// timeastro.cpp
doubles approx_noons_from_utc(doubles unix_times, double lon_deg, double lat_deg);
extern "C" SEXP _mixtime_approx_noons_from_utc(SEXP unix_times, SEXP lon_deg, SEXP lat_deg) {
  BEGIN_CPP11
    return cpp11::as_sexp(approx_noons_from_utc(cpp11::as_cpp<cpp11::decay_t<doubles>>(unix_times), cpp11::as_cpp<cpp11::decay_t<double>>(lon_deg), cpp11::as_cpp<cpp11::decay_t<double>>(lat_deg)));
  END_CPP11
}
// timeastro.cpp
doubles approx_utc_from_noons(doubles noon_counts, double lon_deg, double lat_deg);
extern "C" SEXP _mixtime_approx_utc_from_noons(SEXP noon_counts, SEXP lon_deg, SEXP lat_deg) {
  BEGIN_CPP11
    return cpp11::as_sexp(approx_utc_from_noons(cpp11::as_cpp<cpp11::decay_t<doubles>>(noon_counts), cpp11::as_cpp<cpp11::decay_t<double>>(lon_deg), cpp11::as_cpp<cpp11::decay_t<double>>(lat_deg)));
  END_CPP11
}
// timezone-info.cpp
writable::doubles get_tz_offset(const doubles& posixct, const strings& zone);
extern "C" SEXP _mixtime_get_tz_offset(SEXP posixct, SEXP zone) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_tz_offset(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(posixct), cpp11::as_cpp<cpp11::decay_t<const strings&>>(zone)));
  END_CPP11
}
// timezone-info.cpp
writable::strings get_tz_abbreviation(const doubles& posixct, const strings& zone);
extern "C" SEXP _mixtime_get_tz_abbreviation(SEXP posixct, SEXP zone) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_tz_abbreviation(cpp11::as_cpp<cpp11::decay_t<const doubles&>>(posixct), cpp11::as_cpp<cpp11::decay_t<const strings&>>(zone)));
  END_CPP11
}
// timezone-info.cpp
writable::list get_tz_transitions(const double start_posixct, const double end_posixct, const std::string& zone_name);
extern "C" SEXP _mixtime_get_tz_transitions(SEXP start_posixct, SEXP end_posixct, SEXP zone_name) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_tz_transitions(cpp11::as_cpp<cpp11::decay_t<const double>>(start_posixct), cpp11::as_cpp<cpp11::decay_t<const double>>(end_posixct), cpp11::as_cpp<cpp11::decay_t<const std::string&>>(zone_name)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mixtime_approx_noons_from_utc",    (DL_FUNC) &_mixtime_approx_noons_from_utc,    3},
    {"_mixtime_approx_sunrises_from_utc", (DL_FUNC) &_mixtime_approx_sunrises_from_utc, 4},
    {"_mixtime_approx_sunsets_from_utc",  (DL_FUNC) &_mixtime_approx_sunsets_from_utc,  4},
    {"_mixtime_approx_utc_from_noons",    (DL_FUNC) &_mixtime_approx_utc_from_noons,    3},
    {"_mixtime_approx_utc_from_sunrises", (DL_FUNC) &_mixtime_approx_utc_from_sunrises, 4},
    {"_mixtime_approx_utc_from_sunsets",  (DL_FUNC) &_mixtime_approx_utc_from_sunsets,  4},
    {"_mixtime_get_tz_abbreviation",      (DL_FUNC) &_mixtime_get_tz_abbreviation,      2},
    {"_mixtime_get_tz_offset",            (DL_FUNC) &_mixtime_get_tz_offset,            2},
    {"_mixtime_get_tz_transitions",       (DL_FUNC) &_mixtime_get_tz_transitions,       3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mixtime(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
