# Generated by cpp11: do not edit by hand

mt_glue_fmt <- function(input, env) {
  .Call(`_mixtime_mt_glue_fmt`, input, env)
}

approx_lunations_from_utc <- function(unix_times) {
  .Call(`_mixtime_approx_lunations_from_utc`, unix_times)
}

approx_utc_from_lunations <- function(lunation_counts) {
  .Call(`_mixtime_approx_utc_from_lunations`, lunation_counts)
}

approx_lunar_phase_from_utc <- function(unix_times) {
  .Call(`_mixtime_approx_lunar_phase_from_utc`, unix_times)
}

approx_utc_from_lunar_phase <- function(lunation_counts) {
  .Call(`_mixtime_approx_utc_from_lunar_phase`, lunation_counts)
}

approx_sunrises_from_utc <- function(unix_times, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_sunrises_from_utc`, unix_times, lat_deg, lon_deg, alt_deg)
}

approx_utc_from_sunrises <- function(sunrise_counts, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_utc_from_sunrises`, sunrise_counts, lat_deg, lon_deg, alt_deg)
}

approx_sunsets_from_utc <- function(unix_times, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_sunsets_from_utc`, unix_times, lat_deg, lon_deg, alt_deg)
}

approx_utc_from_sunsets <- function(sunset_counts, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_utc_from_sunsets`, sunset_counts, lat_deg, lon_deg, alt_deg)
}

approx_noons_from_utc <- function(unix_times, lat_deg, lon_deg) {
  .Call(`_mixtime_approx_noons_from_utc`, unix_times, lat_deg, lon_deg)
}

approx_utc_from_noons <- function(noon_counts, lat_deg, lon_deg) {
  .Call(`_mixtime_approx_utc_from_noons`, noon_counts, lat_deg, lon_deg)
}

approx_midnights_from_utc <- function(unix_times, lat_deg, lon_deg) {
  .Call(`_mixtime_approx_midnights_from_utc`, unix_times, lat_deg, lon_deg)
}

approx_utc_from_midnights <- function(midnight_counts, lat_deg, lon_deg) {
  .Call(`_mixtime_approx_utc_from_midnights`, midnight_counts, lat_deg, lon_deg)
}

approx_dawns_from_utc <- function(unix_times, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_dawns_from_utc`, unix_times, lat_deg, lon_deg, alt_deg)
}

approx_utc_from_dawns <- function(dawn_counts, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_utc_from_dawns`, dawn_counts, lat_deg, lon_deg, alt_deg)
}

approx_dusks_from_utc <- function(unix_times, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_dusks_from_utc`, unix_times, lat_deg, lon_deg, alt_deg)
}

approx_utc_from_dusks <- function(dusk_counts, lat_deg, lon_deg, alt_deg) {
  .Call(`_mixtime_approx_utc_from_dusks`, dusk_counts, lat_deg, lon_deg, alt_deg)
}

get_tz_offset <- function(posixct, zone) {
  .Call(`_mixtime_get_tz_offset`, posixct, zone)
}

get_tz_abbreviation <- function(posixct, zone) {
  .Call(`_mixtime_get_tz_abbreviation`, posixct, zone)
}

get_tz_transitions <- function(start_posixct, end_posixct, zone_name) {
  .Call(`_mixtime_get_tz_transitions`, start_posixct, end_posixct, zone_name)
}
