# Generated by cpp11: do not edit by hand

approx_sunrises_from_utc <- function(unix_times, lon_deg, lat_deg, alt_deg) {
  .Call(`_mixtime_approx_sunrises_from_utc`, unix_times, lon_deg, lat_deg, alt_deg)
}

approx_utc_from_sunrises <- function(sunrise_counts, lon_deg, lat_deg, alt_deg) {
  .Call(`_mixtime_approx_utc_from_sunrises`, sunrise_counts, lon_deg, lat_deg, alt_deg)
}

approx_sunsets_from_utc <- function(unix_times, lon_deg, lat_deg, alt_deg) {
  .Call(`_mixtime_approx_sunsets_from_utc`, unix_times, lon_deg, lat_deg, alt_deg)
}

approx_utc_from_sunsets <- function(sunset_counts, lon_deg, lat_deg, alt_deg) {
  .Call(`_mixtime_approx_utc_from_sunsets`, sunset_counts, lon_deg, lat_deg, alt_deg)
}

approx_noons_from_utc <- function(unix_times, lon_deg, lat_deg) {
  .Call(`_mixtime_approx_noons_from_utc`, unix_times, lon_deg, lat_deg)
}

approx_utc_from_noons <- function(noon_counts, lon_deg, lat_deg) {
  .Call(`_mixtime_approx_utc_from_noons`, noon_counts, lon_deg, lat_deg)
}

get_tz_offset <- function(posixct, zone) {
  .Call(`_mixtime_get_tz_offset`, posixct, zone)
}

get_tz_abbreviation <- function(posixct, zone) {
  .Call(`_mixtime_get_tz_abbreviation`, posixct, zone)
}

get_tz_transitions <- function(start_posixct, end_posixct, zone_name) {
  .Call(`_mixtime_get_tz_transitions`, start_posixct, end_posixct, zone_name)
}
